### ISSUE TITLE
Method call via PubSub

### ISSUE THREAD

**Issue by KirillFridman** [barnstee/UA-CloudPublisher#4]
**Feature request**

Call OPC UA methods by publishing MQTT messages with method uri and inputs. Get back method call execution results by subscribing corresponding topic.

**Steps to reproduce / suggestion**

1. Add OPC UA method to publish nodes
2. Publish method meta data to MQTT
3. Publish method call message to MQTT according meta model
4. Subscribe to MQTT topic to get methods outputs after call

**Comment by KirillFridman** [comment]
> This is already implemented in the separate app UA Cloud Commander: https://github.com/barnstee/UA-CloudCommander.

If I got it right, `UA Cloud Commander` is a MQTT/JSON to OPC UA gateway, but not OPC UA PubSub node accroding to specs.

**Comment by barnstee** [comment]
Correct, the method execution result JSON is not in PubSub format, but this is by design as publishing the method result as a dataset doesn't really make sense.

**Comment by barnstee** [comment]
Closing due in inactivity.
